<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Info\Module'                        => __DIR__ . '/Module.php',
    'Info\Controller\InfoController' => __DIR__ . '/src/Info/Controller/InfoController.php',
    'InfoTest\Framework\TestCase'        => __DIR__ . '/tests/Info/Framework/TestCase.php',
    'InfoTest\SampleTest'                => __DIR__ . '/tests/Info/SampleTest.php',
);
