<div class="para">
    	<p>
            South Norfolk Youth Symphonic Band + was formed by Mike Booty - who is still Chairman and Musical Director - 
            in 1974. The Band has raised many thousands of pounds for charities and regularly gives around thirty 
            concerts each year. SNYSB has twice played and been presented to HRH The Princess Royal, 
            once in the Royal Albert Hall. We have performed 'Tubby the Tuba', narrated by the late Roy Castle 
            and performed in Europe on many occasions winning third prize in an International Music Festival in 
            Valkenburg, Holland. The Band was presented with the Queen's Award for Voluntary Service in 2006. 
            It has toured Germany five times, most recently in July 2000, the Far East, Singapore, Borneo and 
            Thailand in August 2008. SNYSB returned to the far east in 2012, and again in 2016. 
            We also plan to travel for a long weekend in Germany in 2017. The Band is completely independent, 
            the only major source of Band income are the two events held each year solely for this purpose 
            (the 'Songs from the shows' concert and a Christmas concert).
        </p>
</div>
    <hr>
    <div class="para">
    	<p>
            SNYSB has been granted charitable status, which means it is easier for us to receive financial donations.
            <br>Our registered charity number is 1116270. Gift Aid forms are available from Mandy Carter 01379 854600.
        </p>
    </div>
