<h2 class="panel-heading text-center">
                Charitable Status
            </h2>
<div class="panel panel-body para"> 
    <p>
        SNYSB has been granted charitable status,  which means it is easier for us to receive financial donations.
        Our registered charity number is 1116270.</p>
        <p><img src="<?= $this->basePath('img/band/giftaid.png') ?>" alt="band" width="600" height="350" align="middle"></p>
       <p> Gift Aid forms are available from Mandy Carter.
    </p>
</div>
