<h2 class="panel-heading text-center">
                Charitable Status
            </h2>
<div class="panel panel-body para"> 
    <p><h4>
        SNYSB has been granted charitable status,  which means it is easier for us to receive financial donations.
        Our registered charity number is 1116270.</h4></p>
        <p><img src="<?= $this->basePath('img/band/giftaid.png') ?>" alt="band" width="200" align="middle"></p>
       <p><h4> Gift Aid forms are available from Mandy Carter.</h4>
    </p>
</div>
