<div class="panel panel-body para"> 
<h2 class="panel-heading text-center">
                See SNYSB+ Live!
            </h2>
        <div class="panel-body">
            <div class="col-md-4">
              <p><h3>17th December 2017</h3></p>
              <p><h4>SNYSB Christmas Concert</h4></p>
              <p><h4>United Reformed Church</h4></p>
              <p><h4>Diss</h4></p>
              <p><h4>7pm</h4></p>
            </div>
            <div class="col-md-8">
              <p><img src="<?= $this->basePath('img/SNYSB CHRISTMAS CONCERT.jpg') ?>" alt="Mountain View" width="500" height="600"></p>
            </div>
		</div>
		<div class="panel-body">
			<div class="col-md-12">
				<p><h4>Please note that these concerts are open to the general public and the times stated are the time that the concert starts. For other concerts and timings for Band Members please see the Newsletter page for these times. 
					For more information about booking either the main band, small concerts and full concerts with the full band or our Swing Band for private functions please contact our Booking Secretary:
					Emma O&apos;Hara - shamrock.uk@btinternet.com</h4></p>
			</div>
		</div>
</div>