<h2 class="panel-heading text-center">
	See SNYSB+ Live!
</h2>
<div class="panel panel-body para"> 
        <div class="panel-body">
            <div class="col-md-4">
              <p><h3>8th December 2018</h3></p>
              <p>Christmas at Tacolneston Hall</p>
              <p>South Norfolk Council</p>
              <p>Long Stratton</p>
              <p>Long Stratton</p>
              <p>3:15pm - 5:30pm</p>
            </div>
            <div class="col-md-4">
              <p><h3>16th December 2018</h3></p>
              <p>SNYSB Christmas Concert</p>
              <p>United Reformed Church</p>
              <p>Diss</p>
              <p>7:00pm</p>
            </div>
		</div>
		<div class="panel-body">
			<div class="col-md-12">
				<p><h4>Please note that these concerts are open to the general public and the times stated are the time that the concert starts. For other concerts and timings for Band Members please see the Newsletter page for these times. 
					For more information about booking either the main band, small concerts and full concerts with the full band or our Swing Band for private functions please contact our Booking Secretary:
					Emma O&apos;Hara - shamrock.uk@btinternet.com</h4></p>
			</div>
		</div>
</div>
