<div class="panel panel-default">
    <div class="panel-heading">
            <h3 class="panel-title">'contact Us!</h3>
        </div>
        <div class="panel-body">
            <div class="col-md-3">
              <p>Musical Director & Chairman (Trustee) - Mike Booty</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Diss, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01379 641580</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:m.booty42@gmail.com">m.booty42@gmail.com</a></p>
            </div>
            <div class="col-md-3">
              <p>Assistant Musical Director - Ben Dewhurst</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Tharston, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01508 531553</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:bendewhurst@yahoo.com">bendewhurst@yahoo.com</a></p>
            </div>
            <div class="col-md-3">
              <p>Secretary (Trustee) - Emma O'Hara</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>East Harling, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone:  01953 717831</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:shamrock.uk@btinternet.com">shamrock.uk@btinternet.com</a></p>
            </div>
            <hr>
            <div class="col-md-3">
              <p>Treasurer (Trustee) - Mandy Carter</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Harleston, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01379 854600</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:mcarter@carrotech.com">mcarter@carrotech.com</a></p>
            </div>
            <div class="col-md-3">
              <p>Vice Chairman (Trustee) & Child Protection Officer - Malcolm Birchall </p>
              <p><span class="glyphicon glyphicon-map-marker"></span>North Lopham, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01379 687608 </p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:malcolmbirchall@btinternet.com">malcolmbirchall@btinternet.com</a></p>
            </div>
            <div class="col-md-3">
              <p>Publicity and Promotions Officer (Trustee) - Mandy Whitham</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Rushall, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01379 740004</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:ladyofthelake059@btinternet.com">ladyofthelake059@btinternet.com</a></p>
            </div>
            <hr>
            <div class="col-md-3">
              <p>Parent Representative (Trustee) - Phil Anderson</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>New Buckenham, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01953 860370</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:phil.anderson66@btinternet.com">phil.anderson66@btinternet.com</a></p>
            </div>
            <div class="col-md-3">
              <p>Membership Secretary - Joanna Mason</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Diss, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:joannamason@msn.com">joannamason@msn.com</a></p>
            </div>
            <div class="col-md-3">
              <p>Music Librarian, Instrument & Website Manager - Aislinn Russell</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Diss, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:ais_russell@hotmail.com">ais_russell@hotmail.com</a></p>
            </div>
            <hr>
            <div class="col-md-3">
              <p>Band Representatives - Georgia Golby & Alex Whitham</p>
            </div>
    	</div>
        <div class="panel-body">
            <div class="col-md-3">
              <p>Creative Youth Officer & Swing Band Director - Delcine Dunsmore</p>
            </div>
    	</div>
</div>