<div class="panel panel-default">
    <div class="panel-heading">
            <h3 class="panel-title">'contact Us!</h3>
        </div>
        <div class="panel-body">
            <div class="col-md-4">
              <p>Fan? Drop a note.</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Chicago, US</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: +00 1515151515</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: mail@mail.com</p>
            </div>
    </div>
</div>