<div class="panel panel-body para"> 
<h2 class="panel-heading text-center">
                Contact SNYSB+!
            </h2>
        <div class="panel-body"><h4>
            <div class="col-md-4">
              <p>Musical Director & Chairman (Trustee) - Mike Booty</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Diss, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01379 641580</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:m.booty42@gmail.com">m.booty42@gmail.com</a></p>
            </h4></div>
            <div class="col-md-4">
            <h4>  <p>Assistant Musical Director - Ben Dewhurst</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Tharston, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01508 531553</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:bendewhurst@yahoo.com">bendewhurst@yahoo.com</a></p>
            </h4></div>
            <div class="col-md-4">
             <h4> <p>Secretary (Trustee) - Emma O'Hara</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>East Harling, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone:  01953 717831</p>
             </h4> <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:shamrock.uk@btinternet.com">shamrock.uk@btinternet.com</a></p>
            </div>
            </div>
			<div class="panel-body"> 
            <div class="col-md-4">
             <h4> <p>Treasurer (Trustee) - Mandy Carter</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Harleston, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01379 854600</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:mcarter@carrotech.com">mcarter@carrotech.com</a></p>
            </h4></div>
            <div class="col-md-4">
             <h4> <p>Vice Chairman (Trustee) & Child Protection Officer - Malcolm Birchall </p>
              <p><span class="glyphicon glyphicon-map-marker"></span>North Lopham, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01379 687608 </p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:malcolmbirchall@btinternet.com">malcolmbirchall@btinternet.com</a></p>
            </h4></div>
            <div class="col-md-4">
            <h4>  <p>Publicity and Promotions Officer (Trustee) - Mandy Whitham</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Rushall, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01379 740004</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:amandajwhitham@gmail.com">amandajwhitham@gmail.com</a></p>
           </h4> </div>
            </div>
			<div class="panel-body"> 
            <div class="col-md-4">
             <h4> <p>Parent Representative (Trustee) - Phil Anderson</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>New Buckenham, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-phone"></span>Phone: 01953 860370</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:phil.anderson66@btinternet.com">phil.anderson66@btinternet.com</a></p>
            </h4></div>
            <div class="col-md-4">
             <h4> <p>Membership Secretary - Joanna Mason</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Diss, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:joannamason@msn.com">joannamason@msn.com</a></p>
            </h4></div>
            <div class="col-md-4">
             <h4> <p>Website Manager - Aislinn Russell</p>
              <p><span class="glyphicon glyphicon-map-marker"></span>Diss, Norfolk, UK</p>
              <p><span class="glyphicon glyphicon-envelope"></span>Email: <a href="mailto:ais_russell@hotmail.com">ais_russell@hotmail.com</a></p>
           </h4> </div>
            </div>
			<div class="panel-body"> 
            <div class="col-md-4">
            <h4>  <p>Band Librarians - Aislinn Russell, Alex Whitham &amp; Delcine Dunsmore</p></h4>
            </div>
            <div class="col-md-4">
             <h4> <p>Band Representatives - Alice O&apos;Hara &amp; Tom Anderson</p></h4>
            </div>
            <div class="col-md-4">
              <h4><p>Creative Youth Officer &amp; Swing Band Director - Delcine Dunsmore</p></h4>
            </div>
    	</div>
</div>