<h2 class="panel-heading text-center">
                Friends of SNYSB+!
            </h2>
<div class="panel panel-body para"> 
    	<p><h4>
           The Band has a Friends Association for all supporters of the Band that are not current parents. Friends receive a copy of the Bands Newsletter each month that keeps them up-to-date with Band concerts and events. Friends are also able to buy tickets before they go on sale to the general public.
There is an annual subscription charge of &pound;5.00 which covers postage and printing.
Cheques should be payable to: SNYSB and sent with your name address and contact details to the treasurer (Details on our contact page).
       </h4> </p>
        <div style="text-align: center"> 
<p><img src="<?= $this->basePath('img/band/Tubas-filtered.jpg') ?>" alt="band" align="middle"></p>
</div>
</div>
