<div class="panel panel-body para"> 
    	<p><h4>
            The Band is a mixed ability band, currently with over 100 members, aged between eight and 75! 
            Some have no Associated Board examination successes while others have passed Grade Eight. Auditions are not neccessary, 
            just keen-ness and the desire to make great music Joining this band is much more than just coming along and playing on a 
            Tuesday evening. It is about like minded people getting together to play and enjoy their music in an atmosphere of 
            friendship and to spread that enjoyment to the listening audience in concerts.
       </h4> </p>
</div>
    <hr>
    <div  style="text-align: center"> 
<p><img src="<?= $this->basePath('img/band/band2.jpg') ?>" alt="band" width="600" height="350" align="middle"></p>
</div>
  <hr>
  <div class="panel panel-body para">
    	<p><h4>
            The Band motto is 'Music Is Fun'. In an attempt to ensure this there are two basic rules for entry to the Band. 
            Firstly, the Band will never turn away a prospective member. This often leads to having a huge number of players 
            in any section and a shortage in other areas. Secondly,
            no minimum standard is required. New and inexperienced players are told to play any note in the bar that they can 
            and to follow their neighbour. Our older musicians will happily support all younger players.
             Some of the current Section Leaders and Soloists started in this way. </h4>
</div>
    <hr>
<div style="text-align: center"> 
<p><img src="<?= $this->basePath('img/band/Hypermall.jpg') ?>" alt="band" align="middle"></p>
</div>
  <hr>
  <div class="col-md-6">
<h3 class="panel-heading text-center">
            How much will it cost?
            </h3>
    	<p><h4>
			Costs are just &pound;20.00. For this you will be given a Band Tie and Lapel Badge, an instrument case sticker and your 
			Membership Subscription to the band is then paid up to the following Annual General Meeting, usually held in November. 
			The Annual Subscription charge is &pound;50.00 a year. The only other costs involved with membership are travelling to 
			rehearsals and concerts, Band trips, Residential Weekends and the like.</h4>
</div>
<div class="panel panel-body para">
<div class="col-md-6">
<h3 class="panel-heading text-center">
            Do I need my own instrument?
            </h3>
    	<p><h4>
             No, although the Band maintains many instruments it was fortunate, in Summer 1997, to 
            receive a &pound;50,000 Lottery Grant to buy some of the more expensive instruments that parents find difficult to buy. 
            The instruments obtained include oboes, bassoon, bass and contra bass clarinets, french horns, a tuba, an impressive 
            array of percussion as well as many others.<h4>
        </p>
</div>
<hr>
<div class="col-md-6">
<h3 class="panel-heading text-center">
                Where are rehearsals?
            </h3>
    	<p><h4>
			If you want to come and play with the band for a few weeks to consider whether to join please 
			turn up by 7.00pm any Tuesday night at Diss Youth Centre, Shelfanger Road, Diss. The Band always meet during the school 
			holidays but normally misses two rehearsals after our Christmas Concert.</h4>
        </p>
</div>
<div class="col-md-6">
<h3 class="panel-heading text-center">
            What will I be doing as part of SNYSB+?
            </h3>
    	<p><h4>
			As a Band Member you may attend Band Functions and play in Concerts as soon as you join. Most will be within 
			twenty miles of our base in Diss although some are further a field. You are expected to get yourself to the Concert 
			but in most cases a complimentary ticket will be available to the driver on the basis of one per family.
			[mention army days, and trips]</h4>
        </p>
</div>
<hr>
</div>
