<div class="panel panel-default">
    <div class="panel-body">
    	<p>
            The Band is a mixed ability band currently with over 100 members, aged between eight and twenty three. 
            Some have no Associated Board examination successes while others have passed Grade Eight. Joining this 
            Band is much more than just coming along and playing on a Tuesday evening. It is about like minded young 
            people getting together to play and enjoy their music in an atmosphere of friendship and to spread that 
            enjoyment to the listening audience in concerts.
        </p>
    </div>
</div>
    <hr>
<div class="panel panel-default">
    <div class="panel-body">
    	<p>
            The Band motto is 'Music Is Fun'. In an attempt to ensure this there are two basic rules for entry to the Band. 
            Firstly, the Band will never turn away a prospective member. This often leads to having a huge number of players 
            in any section and a shortage in other areas. Secondly, no prospective member is required to audition to join and 
            no minimum standard is required. New and inexperienced players are told to play any note in the bar that they can 
            and to follow their neighbour. Some of the current Section Leaders and Soloists started in this way. 
			<br>
			Costs are just &pound;20.00. For this you will be given a Band Tie and Lapel Badge, an instrument case sticker and your 
			Membership Subscription to the band is then paid up to the following Annual General Meeting, usually held in November. 
			The Annual Subscription charge is £10.00 a year. The only other costs involved with membership are travelling to 
			rehearsals and concerts, Band trips, Residential Weekends and the like.
			<br>
			As a Band Member you may attend Band Functions and play in Concerts as soon as you join. Most will be within 
			twenty miles of our base in Diss although some are further a field. You are expected to get yourself to the Concert 
			but in some cases a complimentary ticket will be available to the driver on the basis of one per family.
        </p>
    </div>
</div>
    <hr>
<div class="panel panel-default">
    <div class="panel-body">
    	<p>
            Do I need my own instrument? No, although the Band maintains many instruments it was fortunate, in Summer 1997, to 
            receive a £50,000 Lottery Grant to buy some of the more expensive instruments that parents find difficult to buy. 
            The instruments obtained include oboes, bassoon, bass and contra bass clarinets, french horns, a tuba, an impressive 
            array of percussion as well as many others.
			<br>
			Where are rehearsals? If you want to come and play with the band for a few weeks to consider whether to join please 
			turn up by 7.00pm any Tuesday night at Diss Youth Centre, Shelfanger Road, Diss. The Band always meet during the school 
			holidays but normally misses two rehearsals after our Christmas Concert.
        </p>
    </div>
</div>