<h2 class="panel-heading text-center">
                Monthly Newsletters
            </h2>
<div class="panel panel-body para"> 
    	<p><h4>
           Below are the Bands monthly newsletters, click on the links below to download.</p>
            <a title="PDF/dec17" href="<?= $this->basePath('PDF/oct18.pdf') ?>" target="_blank">October 2018</a><br>
       </h4> </p>
        <div style="text-align: center"> 
<p><img src="<?= $this->basePath('img/band/Tubas-filtered.jpg') ?>" alt="band" align="middle"></p>
</div>
</div>
    <hr>
