<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SNYSB+')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'img/blue-logo.png'])
            ->prependStylesheet($this->basePath('css/bootstrap.css'))
            ->prependStylesheet($this->basePath('css/snysbstyle.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
    <div class="container">
    <img src="<?= $this->basePath('img/black-logo.png') ?>" class="logoplace" height="150" />
    <nav class="navbar navbar-default">
     <a class="navbar-brand" href="<?= $this->url('home') ?>">
      	<img src="<?= $this->basePath('img/home.png') ?>" height="35" alt="SNYSB+  <?= \Application\Module::VERSION ?>"/>
      </a>
          <div class="navbar-header">
   
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="dropdown"><a href="<?= $this->url('about') ?>" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
        <ul class="dropdown-menu">
        <li><a href="<?= $this->url('about') ?>">About Us</a></li>
        <li><a href="<?= $this->url('join') ?>">Join</a></li>
        <li><a href="<?= $this->url('friends') ?>">Friends</a></li>
        
      </ul>
              <li><a href="<?= $this->url('concerts') ?>">Concerts</a></li>
              <li><a href="<?= $this->url('contact') ?>">Contact</a></li>
        <li><a href="<?= $this->url('newsletter') ?>">Newsletter</a></li>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="https://www.facebook.com/SouthNorfolkYouthSymphonicBand/" target="_blank" ><img src="<?= $this->basePath('img/facebook.png') ?>" height="28" alt="SNYSB+  <?= \Application\Module::VERSION ?>"/></a></li>
      </ul>
    </div>
    </nav>
    </div>

        <div class="container">
            <?= $this->content ?>
            </div>
        <?= $this->inlineScript() ?>
    </body>
    <footer>
    <img src="<?= $this->basePath('img/footer.png') ?>" class="logoplace" height="100" />
    </footer>
</html>
