<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SNYSB+')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/snysbstyle.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
    <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="<?= $this->url('home') ?>">
      	<img src="<?= $this->basePath('img/favicon.ico') ?>" height="328" alt="SNYSB+  <?= \Application\Module::VERSION ?>"/>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="<?= $this->url('about') ?>">About</a></li>
        <li><a href="<?= $this->url('join') ?>">Join</a></li>
        <li><a href="<?= $this->url('contact') ?>">Contact</a></li>
      </ul>
<!--       <ul class="nav navbar-nav navbar-right"> -->
<!--         <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
<!--       </ul> -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="https://www.facebook.com/snysb1974/"><img src="<?= $this->basePath('img/facebook.png') ?>" height="28" target="_blank" alt="SNYSB+  <?= \Application\Module::VERSION ?>"/></a></li>
      </ul>
    </div>
</nav>
        <div class="container">
            <?= $this->content ?>
            </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
