<div class="jumbotron">
    <h1>Welcome to South Norfolk Youth Symphonic Band +</h1>
</div>
<div class="panel-body">
    <p>
        We're a youth symphonic band based in Diss. Although we're a youth band, we allow woodwind, brass or percussion musicians
        of all ages and skills. We meet on Tuesday evenings (7-9pm) at the Diss Youth and Community Centre on Shelfhanger Road. 
    </p>
</div>