<!-- <div id="myCarousel" class="carousel slide" data-ride="carousel"> -->
    <!-- Indicators -->
<!--     <ol class="carousel-indicators"> -->
<!--       <li data-target="#myCarousel" data-slide-to="0" class="active"></li> -->
<!--       <li data-target="#myCarousel" data-slide-to="1"></li> -->
<!--     </ol> -->

    <!-- Wrapper for slides -->
<!--     <div class="carousel-inner" role="listbox"> -->
<!--       <div class="item active"> -->
<!--         <img src="img/1.jpg" alt="Image" class="img-rounded"> -->
<!--       </div> -->

<!--       <div class="item"> -->
<!--         <img src="img/1.jpg" alt="Image" class="img-rounded"> -->
<!-- <!--         <div class="carousel-caption"> --> 
<!-- <!--           <h3>More Sell $</h3> -->
<!-- <!--           <p>Lorem ipsum...</p> --> 
<!-- <!--         </div>       --> 
<!--       </div> -->
<!--     </div> -->

    <!-- Left and right controls -->
<!--     <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"> -->
<!--       <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> -->
<!--       <span class="sr-only">Previous</span> -->
<!--     </a> -->
<!--     <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"> -->
<!--       <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> -->
<!--       <span class="sr-only">Next</span> -->
<!--     </a> -->
<!-- </div> -->

<div style="text-align: center"> 
<p><img src="<?= $this->basePath('img/band/band1.jpg') ?>" alt="band" width="850" height="450" align="middle"></p>
</div>
   <hr>
            <div class="panel panel-body para">     
            <h1 class="panel-heading text-center">
                We Are South Norfolk Youth Symphonic Band+ !
            </h1>          
                <p><h4>
		      We're a youth symphonic band based in Diss. Although we're a youth band, we welcome woodwind, 
		       brass or percussion musicians of all ages and skills. 
		       We meet on Tuesday evenings (7-9pm, 50 weeks of the year) at the Diss Youth and Community Centre on Shelfhanger Road, in Diss.</h4> </p>
  
   <div style="text-align: center"><div class="fb-like-box" data-href="https://www.facebook.com/pages/UK-South-Norfolk-Youth-Symphonic-Band-SNYSB/415935458421371?fref=ts" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div></div>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=218530448172624&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  </div>     
